packages:
  - software
  - workflow
  - model
  - ui
  - test
  - block

catalog:
  "@platforma-sdk/model": ^1.22.18
  "@platforma-sdk/ui-vue": ^1.22.30
  "@platforma-sdk/workflow-tengo": ^2.10.0
  "@platforma-sdk/block-tools": ^2.5.9
  "@platforma-sdk/test": ^1.22.31
  "@platforma-sdk/tengo-builder": ^1.17.5
  "@platforma-sdk/package-builder": ^2.11.1
  "@milaboratories/graph-maker": ^1.1.44
  '@platforma-sdk/eslint-config': ^1.0.1

  '@milaboratories/software-pframes-conv': ^2.1.7
  '@platforma-open/milaboratories.software-small-binaries': ^1.15.6
  "@platforma-open/milaboratories.runenv-python-3": ^1.0.0
  
  "vue": ^3.5.13
  "vue-tsc": ^2.2.0
  
  "typescript": ^5.6.3
  "tsup": ~8.3.5
  "turbo": ^2.4.1

  "vite": ^6.1.0
  "vitest": ^3.0.5
  "@vitejs/plugin-vue": ^5.2.1

  "@changesets/cli": ^2.27.12
