packages:
  - software
  - workflow
  - model
  - ui
  - test
  - block

catalog:
  "@platforma-sdk/model": ^1.48.4
  "@platforma-sdk/ui-vue": ^1.48.10
  "@platforma-sdk/workflow-tengo": ^5.7.3
  "@platforma-sdk/block-tools": ^2.6.27
  "@platforma-sdk/test": ^1.48.9
  "@platforma-sdk/tengo-builder": ^2.4.2
  "@platforma-sdk/package-builder": ^3.10.7
  "@platforma-sdk/blocks-deps-updater": ^2.0.0
  "@milaboratories/graph-maker": ^1.1.196
  '@platforma-sdk/eslint-config': ^1.2.0

  '@milaboratories/software-pframes-conv': ^2.2.9
  '@platforma-open/milaboratories.software-small-binaries': ^1.15.25
  "@platforma-open/milaboratories.runenv-python-3": ^1.7.4
  
  "vue": ^3.5.13
  "vue-tsc": ^2.2.0
  
  "typescript": ~5.5.4
  "tsup": ~8.3.5
  "turbo": ^2.4.4

  "vite": ^6.1.0
  "vitest": ^3.0.5
  "@vitejs/plugin-vue": ^5.2.1

  "@changesets/cli": ^2.28.1
