packages:
  - software
  - workflow
  - model
  - ui
  - test
  - block

catalog:
  "@platforma-sdk/model": ^1.45.23
  "@platforma-sdk/ui-vue": ^1.45.23
  "@platforma-sdk/workflow-tengo": ^5.5.16
  "@platforma-sdk/block-tools": ^2.6.16
  "@platforma-sdk/test": ^1.45.25
  "@platforma-sdk/tengo-builder": ^2.3.4
  "@platforma-sdk/package-builder": ^3.10.7
  "@platforma-sdk/blocks-deps-updater": ^2.0.0
  "@milaboratories/graph-maker": ^1.1.175
  '@platforma-sdk/eslint-config': ^1.1.0

  '@milaboratories/software-pframes-conv': ^2.2.9
  '@platforma-open/milaboratories.software-small-binaries': ^1.15.23
  "@platforma-open/milaboratories.runenv-python-3": ^1.4.9
  
  "vue": ^3.5.13
  "vue-tsc": ^2.2.0
  
  "typescript": ~5.5.4
  "tsup": ~8.3.5
  "turbo": ^2.4.4

  "vite": ^6.1.0
  "vitest": ^3.0.5
  "@vitejs/plugin-vue": ^5.2.1

  "@changesets/cli": ^2.28.1
